name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run --rm -e CI=true app-test npm run test -- --coverage
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare deployment package
        run: |
          rm -f deploy.zip
          zip -r deploy.zip \
           Dockerfile \
            package.json \
           package-lock.json \
            public \
            src
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "frontend"        # имя приложения в EB
          environment_name: "Frontend-env"    # имя окружения
          region: "us-east-1"               # регион AWS
          version_label: ${{ github.sha }}  # уникальная метка билда
          deployment_package: deploy.zip    # архив кода
          wait_for_deployment: true
          wait_for_deployment_timeout: 30    # было ~15, поставим 30 минут
          wait_for_environment_recovery: true
          wait_for_environment_recovery_timeout: 30

