name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run --rm -e CI=true app-test npm run test -- --coverage
