name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps & build
        run: |
          npm CI
          npm run build

 
      - name: Generate deployment package
        run: |
          rm -f deploy.zip
          zip -r deploy.zip build Dockerfile docker-compose.yml
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
